Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "nerrakebS" do |server|
    server.vm.hostname = "nerrakebS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "nerrakebS"
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = false
    end
    
    server.vm.provision "shell", path: "scripts/install_k3s.sh"
    server.vm.provision "shell", path: "scripts/deploy_apps.sh"
  end
end