Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_download_insecure = true
  
    config.vm.define "nerrakebS" do |server|
        server.vm.hostname = "nerrakebS"
        server.vm.network "private_network", ip: "192.168.56.110"
        
        server.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"  # Critical for ARM64
        v.gui = false
        v.linked_clone = false
        v.ssh_info_public = true
        v.allowlist_verified = true
    
        server.vm.provision "shell", path: "scripts/install_k3s.sh"
        server.vm.provision "shell", path: "scripts/deploy_apps.sh"
        end
    end
end
