Vagrant.configure("2") do |config|
  # Change to your actual login
  login = "kkouaz"

  config.vm.define "#{login}S" do |s|
    s.vm.box = "debian/bullseye64"
    s.vm.hostname = "#{login}S"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    # This script installs K3s in server mode automatically
    s.vm.provision "shell", path: "scripts/setup_p2.sh"
  end
end