
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

    config.vm.define "kkouazS" do |server|
        server.vm.hostname = "kkouazS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "kkouazS"
            vb.memory = "1024"
            vb.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/server_setup.sh"
    end

    config.vm.define "kkouazSW" do |worker|
        worker.vm.hostname = "kkouazSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.name = "kkouazSW"
            vb.memory = "1024"
            vb.cpus = 1
        end
        worker.vm.provision "shell", path: "scripts/worker_setup.sh"
    end

end
